### PR TITLE
Added performance attribute

### PR DESCRIPTION
**Pull request by sblackler**

### CODE REVIEW

**Comment by herecydev** [comment]
Whilst this isn't bad, If I was to do this. I would expect to handle the timings on behalf of the client.

```c#
[Performance(100)] //100ms
public void PerfTest()
{
 //some setup

//act
Benchmark.This(() => _serializer.Serialize(new Poco()));

//test will fail if over 100
}
```

Thoughts?

**Comment by sblackler** [comment]
Well I partially agree. Performance can mean a number of things such as throughput/memory usage, not just time. Plus you'd be limiting it to a specific benchmarking framework. Not necessarily a problem, but something to be aware of. 

That said, we could think about additional attributes like `WithTimeLimit` and specify the timeout in there. 

Cc/ @smudge202 @mattridgway

**Comment by smudge202** [comment]
Erm.. Are we talking about benchmarking or about performance testing? The two are not the same.

Benchmarking is just about taking measurements. I wouldn't expect a Benchmark to pass/fail like in the case of a test. Simply output results somewhere so that a human can decide whether a change is acceptable.

Performance testing (as the name suggests) is a test. But it should not be treated like a unit test. To performance test (as with benchmarking) you need comparable results to be from the same environments under the same constraints. It doesn't make sense to specify it as tests like has been done here. If _foo_ runs in 200ms on my machine, you make a change on your machine which makes _foo_ run twice as slow but because your machine is twice as fast as mine, it passes the tests?

If we relied on CI being the common location for passing tests, it would still be massively inaccurate because unless someone wants to pay for an upgrade, appveyor runs on shared instances of azure vm's, so performance is all over the place.

**Comment by smudge202** [comment]
Additional info on related issue here: https://github.com/sblackler/compose/pull/1#issuecomment-167329186

**Comment by sblackler** [comment]
Sounds better to have two attributes, one for performance and a separate for benchmarking? Then you could do the time limited stuff. 

I am currently thinking about the direct comparison between two sections of code (Ie: is a faster than b)

**Comment by smudge202** [comment]
I don't think benchmarking makes sense in a "Test Attributes" repo, because it isn't a test?

Performance testing, similarly, can'y really be done through the same pipeline as your normal tests (even if running integration, unit, & component, I'd still expect performance testing like load and stress to be done outside of that pipeline).

Comparing the performance of two implementations however does seem (arguably/grey area) reasonable.

**Comment by herecydev** [comment]
Performance varying machines is of course an issue. But simply not offering timing based on appveyor sounds off. What if they have their own CI server? What is appveyor guarantees QoS in the future?

I appreciate your machine my machine problems are always going to exist but measuring changes on the same, consistent machine seems like a reasonable concept.

**Comment by smudge202** [comment]
I see what you're saying, @herecydev. Let's assume we're looking at a teamcity ci pipeline, and despite having multiple build agents you've configured tc to use the same build agent each time. You've also configured tc to not use the build agent for more than one task at a time. You've also made the build agent on a dedicated host to prevent resource sharing across vms on a shared host. (This to me already seems a little far fetched...).

You run a ci build and your test runs within the allotted time. Woot. Later, somebody checks in something unrelated and the build fails due to this test.

* Has some changed resource allocation?
* Has some changed teamcity configuration?
* Does running it again and having it pass mean there isn't an issue?
Did a tertiary service like windows update or file indexer cause the blip?

Point being, if you set up everything perfectly, you still couldn't place trust in the test. Tests that I don't trust I personally, wouldn't want.

**Comment by sblackler** [comment]
Personally, I was thinking of just the simple case of marking my performance tests with the `[Performance]` attribute. It's just a way of categorising tests. Whether or not it's included as part of the CI pipeline is up to the consumer of the library (based on the arguments above).

Without the attribute, how would you specify an automated performance test? You may legitimately have Unit/Component/Integration tests so you couldn't abuse those categories (toggle on/off).

**Comment by herecydev** [comment]
@smudge202 So what exactly is the point in having performance tests? If there are so many criteria that can affect the performance of a test to the point that it varies considerably, then the whole test makes no sense. I.e what do we gain from a [Perfomance] attribute?

Take an entity framework scenario where someone performs a query against some SQL that is run on the server and returned to the client that takes ~1s. We could assert that +-1s is fine. But if a change is made that removes use of IQueryable and instead passes around IEnumerable we would probably expect a skyrocket in total time. This seems like something that you would want to catch, what's the best way of seeing this early on through CI?

**Comment by smudge202** [comment]
I think you hit it on the head there, @herecydev . I don't know of any examples of "having a performance test", nor do I know of a way to make such a thing valuable.

On contrary, performance testing your application through some other concise managed process I'm sure could have value. In short, whilst performance testing can be invaluable, coming up with a mechanism to automated performance tests into your CI pipeline is probably just asking for trouble.

**Comment by herecydev** [comment]
Right, @sblackler I'm keen to hear your thoughts. I see value in having a performance test, but if there's no clean, automated way of making it reliable then it seems like wasted effort.

Let me know!

**Comment by sblackler** [comment]
As already mentioned in the thread, there is an element of variability when talking in terms of performance/time, which I can understand. But we, as library produces cannot dictate the levels of variability in the test, that is for the consumer. 

I feel just adding it as a category is as far as we should go purely from the perspective that we can have a suit of tests that we can run easily. Whether the consumer wants to trust those tests in the CI pipeline is up to them (Remembering that all tests **should** be run by the dev before commit/push).

**Comment by smudge202** [comment]
@sblackler The point I'm making is regardless of who the consumer is, there is no way to make any form of unit test beyond benchmark competitions at all viable. What possible test can you run and trust in the same way you run unit/component/integration?

**Pull request closed without merging**
